version: "3.8"

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-expresse
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_URL=mongodb+srv://chinthana:chinthana99@chinthana.ydhrjtg.mongodb.net/virtualschool?retryWrites=true&w=majority&appName=Chinthana
    networks:
      - mongodb_network

networks:
  mongodb_network:
