version: "3.8"

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-expresse
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=cluster0.mongodb.net
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rachinthanarajapaksha@admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rachinthanarajapaksha
      - ME_CONFIG_MONGODB_URL=mongodb+srv://rachinthanarajapaksha:rootpass@chinthana.ydhrjtg.mongodb.net/?retryWrites=true&w=majority&appName=Chinthana

    networks:
      - mongodb_network

networks:
  mongodb_network:
